-- Persistent cleaning maintenance state for operator dashboard actions.
-- Run this after rpc_wash_actions.sql (requires public.require_operator_or_owner()).

begin;

create table if not exists public.box_cleaning_state (
  box_id integer primary key references public.boxes(id) on delete cascade,
  washes_since_cleaning integer not null default 0
    check (washes_since_cleaning >= 0),
  last_cleaned_at timestamptz,
  updated_at timestamptz not null default now()
);

create index if not exists idx_box_cleaning_state_washes
  on public.box_cleaning_state (washes_since_cleaning desc, updated_at desc);

alter table if exists public.box_cleaning_state enable row level security;
revoke all on table public.box_cleaning_state from public;
revoke all on table public.box_cleaning_state from anon, authenticated;

create table if not exists public.box_cleaning_events (
  id bigint generated by default as identity primary key,
  box_id integer not null references public.boxes(id) on delete cascade,
  performed_by uuid not null references auth.users(id) on delete cascade,
  cleaned_at timestamptz not null default now(),
  note text,
  washes_before integer not null default 0
    check (washes_before >= 0),
  created_at timestamptz not null default now()
);

create index if not exists idx_box_cleaning_events_box_cleaned_at
  on public.box_cleaning_events (box_id, cleaned_at desc);

alter table if exists public.box_cleaning_events enable row level security;
revoke all on table public.box_cleaning_events from public;
revoke all on table public.box_cleaning_events from anon, authenticated;

alter table if exists public.box_cleaning_events
  add column if not exists note text;

insert into public.box_cleaning_state (box_id, washes_since_cleaning, last_cleaned_at, updated_at)
select
  b.id,
  coalesce((select count(*)::int from public.wash_sessions s where s.box_id = b.id), 0),
  null,
  now()
from public.boxes b
on conflict (box_id) do nothing;

create or replace function public.bump_box_cleaning_counter_on_session()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.box_id is null then
    return new;
  end if;

  insert into public.box_cleaning_state (
    box_id,
    washes_since_cleaning,
    last_cleaned_at,
    updated_at
  )
  values (
    new.box_id,
    1,
    null,
    now()
  )
  on conflict (box_id) do update
    set washes_since_cleaning = public.box_cleaning_state.washes_since_cleaning + 1,
        updated_at = now();

  return new;
end;
$$;

drop trigger if exists trg_bump_box_cleaning_counter_on_session on public.wash_sessions;
create trigger trg_bump_box_cleaning_counter_on_session
after insert on public.wash_sessions
for each row
execute function public.bump_box_cleaning_counter_on_session();

create or replace function public.get_box_cleaning_plan(cleaning_interval integer default 75)
returns table (
  box_id integer,
  last_cleaned_at timestamptz,
  washes_since_cleaning integer,
  washes_until_next_cleaning integer,
  is_due boolean
)
language plpgsql
security definer
set search_path = public
as $$
#variable_conflict use_column
declare
  v_interval integer := greatest(coalesce(cleaning_interval, 75), 1);
begin
  perform public.require_operator_or_owner();

  insert into public.box_cleaning_state (box_id)
  select b.id
  from public.boxes b
  on conflict (box_id) do nothing;

  return query
  select
    b.id,
    s.last_cleaned_at,
    coalesce(s.washes_since_cleaning, 0) as washes_since_cleaning,
    greatest(v_interval - coalesce(s.washes_since_cleaning, 0), 0) as washes_until_next_cleaning,
    coalesce(s.washes_since_cleaning, 0) >= v_interval as is_due
  from public.boxes b
  left join public.box_cleaning_state s on s.box_id = b.id
  order by b.id;
end;
$$;

create or replace function public.get_box_cleaning_history(
  box_id integer default null,
  max_rows integer default 30
)
returns table (
  id bigint,
  box_id integer,
  performed_by uuid,
  performed_by_email text,
  cleaned_at timestamptz,
  washes_before integer,
  note text
)
language sql
security definer
set search_path = public
as $$
  with _auth as (
    select public.require_operator_or_owner()
  )
  select
    e.id,
    e.box_id,
    e.performed_by,
    coalesce(p.email, '')::text as performed_by_email,
    e.cleaned_at,
    e.washes_before,
    e.note
  from public.box_cleaning_events e
  left join public.profiles p on p.id = e.performed_by
  cross join _auth
  where ($1 is null or e.box_id = $1)
  order by e.cleaned_at desc, e.id desc
  limit greatest(1, least(coalesce($2, 30), 100));
$$;

create or replace function public.mark_box_cleaned(
  box_id integer,
  note text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
#variable_conflict use_column
declare
  v_box_id integer := $1;
  v_note text := nullif(btrim(coalesce($2, '')), '');
  v_user_id uuid := auth.uid();
  v_now timestamptz := now();
  v_washes_before integer := 0;
begin
  perform public.require_operator_or_owner();

  if v_box_id is null or v_box_id <= 0 then
    raise exception 'box_not_found';
  end if;

  if not exists (
    select 1
    from public.boxes b
    where b.id = v_box_id
  ) then
    raise exception 'box_not_found';
  end if;

  select coalesce(s.washes_since_cleaning, 0)
    into v_washes_before
  from public.box_cleaning_state s
  where s.box_id = v_box_id
  for update;

  if not found then
    select coalesce(count(*)::int, 0)
      into v_washes_before
    from public.wash_sessions ws
    where ws.box_id = v_box_id;
  end if;

  insert into public.box_cleaning_state (
    box_id,
    washes_since_cleaning,
    last_cleaned_at,
    updated_at
  )
  values (
    v_box_id,
    0,
    v_now,
    v_now
  )
  on conflict (box_id) do update
    set washes_since_cleaning = 0,
        last_cleaned_at = excluded.last_cleaned_at,
        updated_at = excluded.updated_at;

  insert into public.box_cleaning_events (
    box_id,
    performed_by,
    cleaned_at,
    washes_before,
    note
  )
  values (
    v_box_id,
    v_user_id,
    v_now,
    v_washes_before,
    v_note
  );

  return jsonb_build_object(
    'box_id', v_box_id,
    'last_cleaned_at', v_now,
    'washes_before', v_washes_before,
    'washes_since_cleaning', 0,
    'note', v_note
  );
end;
$$;

revoke all on function public.bump_box_cleaning_counter_on_session() from public;
revoke all on function public.get_box_cleaning_plan(integer) from public;
revoke all on function public.get_box_cleaning_history(integer, integer) from public;
revoke all on function public.mark_box_cleaned(integer, text) from public;

grant execute on function public.get_box_cleaning_plan(integer) to authenticated;
grant execute on function public.get_box_cleaning_history(integer, integer) to authenticated;
grant execute on function public.mark_box_cleaned(integer, text) to authenticated;

commit;
