-- Operator action audit log (server-side, persistent across devices).
-- Run this in Supabase SQL Editor as project owner.
-- Requires: public.require_operator_or_owner() from rpc_wash_actions.sql

begin;

create table if not exists public.operator_action_log (
  id bigint generated by default as identity primary key,
  actor_id uuid not null references auth.users(id) on delete cascade,
  actor_email text,
  action_name text not null,
  action_status text not null default 'success'
    check (action_status in ('success', 'partial', 'failed')),
  box_id integer references public.boxes(id) on delete set null,
  source text not null default 'app',
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_operator_action_log_created_at
  on public.operator_action_log (created_at desc);

create index if not exists idx_operator_action_log_action_name
  on public.operator_action_log (action_name);

create index if not exists idx_operator_action_log_box_id
  on public.operator_action_log (box_id)
  where box_id is not null;

create index if not exists idx_operator_action_log_status_created
  on public.operator_action_log (action_status, created_at desc);

alter table public.operator_action_log enable row level security;

-- No direct table access from app clients. Access only through RPCs below.
revoke all on table public.operator_action_log from public, anon, authenticated;

do $$
declare
  p record;
begin
  for p in
    select schemaname, tablename, policyname
    from pg_policies
    where schemaname = 'public'
      and tablename = 'operator_action_log'
  loop
    execute format(
      'drop policy if exists %I on %I.%I',
      p.policyname,
      p.schemaname,
      p.tablename
    );
  end loop;
end $$;

create policy "operator_action_log_select_operator_owner"
on public.operator_action_log
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role in ('operator', 'owner')
  )
);

create or replace function public.operator_action_log_append_only_guard()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  raise exception 'operator_action_log_append_only';
end;
$$;

drop trigger if exists trg_operator_action_log_append_only
  on public.operator_action_log;

create trigger trg_operator_action_log_append_only
before update or delete on public.operator_action_log
for each row
execute function public.operator_action_log_append_only_guard();

create or replace function public.log_operator_action(
  action_name text,
  action_status text default 'success',
  box_id integer default null,
  details jsonb default '{}'::jsonb,
  source text default 'app'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_action_name text := coalesce(trim($1), '');
  v_action_status text := lower(coalesce(trim($2), 'success'));
  v_box_id integer := $3;
  v_details jsonb := coalesce($4, '{}'::jsonb);
  v_source text := coalesce(nullif(trim($5), ''), 'app');
  v_user_id uuid := auth.uid();
  v_actor_email text;
  v_id bigint;
  v_created_at timestamptz;
begin
  perform public.require_operator_or_owner();

  if v_action_name = '' then
    raise exception 'invalid_action_name';
  end if;

  if v_action_status not in ('success', 'partial', 'failed') then
    raise exception 'invalid_action_status';
  end if;

  if v_box_id is not null then
    if not exists (select 1 from public.boxes b where b.id = v_box_id) then
      raise exception 'box_not_found';
    end if;
  end if;

  select p.email
    into v_actor_email
  from public.profiles p
  where p.id = v_user_id;

  insert into public.operator_action_log (
    actor_id,
    actor_email,
    action_name,
    action_status,
    box_id,
    source,
    details
  )
  values (
    v_user_id,
    v_actor_email,
    v_action_name,
    v_action_status,
    v_box_id,
    v_source,
    v_details
  )
  returning id, created_at
  into v_id, v_created_at;

  return jsonb_build_object(
    'id', v_id,
    'created_at', v_created_at,
    'action_name', v_action_name,
    'action_status', v_action_status,
    'box_id', v_box_id
  );
end;
$$;

create or replace function public.list_operator_actions(max_rows integer default 50)
returns table (
  id bigint,
  actor_id uuid,
  actor_email text,
  action_name text,
  action_status text,
  box_id integer,
  source text,
  details jsonb,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_limit integer := greatest(1, least(coalesce($1, 50), 200));
begin
  perform public.require_operator_or_owner();

  return query
  select
    l.id,
    l.actor_id,
    l.actor_email,
    l.action_name,
    l.action_status,
    l.box_id,
    l.source,
    l.details,
    l.created_at
  from public.operator_action_log l
  order by l.created_at desc
  limit v_limit;
end;
$$;

create or replace function public.list_operator_actions_filtered(
  max_rows integer default 50,
  offset_rows integer default 0,
  filter_status text default null,
  filter_box_id integer default null,
  search_query text default null,
  from_ts timestamptz default null,
  until_ts timestamptz default null
)
returns table (
  id bigint,
  actor_id uuid,
  actor_email text,
  action_name text,
  action_status text,
  box_id integer,
  source text,
  details jsonb,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_limit integer := greatest(1, least(coalesce($1, 50), 200));
  v_offset integer := greatest(0, coalesce($2, 0));
  v_status text := lower(nullif(trim($3), ''));
  v_box_id integer := $4;
  v_search text := nullif(trim($5), '');
  v_from_ts timestamptz := $6;
  v_until_ts timestamptz := $7;
begin
  perform public.require_operator_or_owner();

  if v_status is not null and v_status not in ('success', 'partial', 'failed') then
    raise exception 'invalid_action_status_filter';
  end if;

  if v_box_id is not null then
    if not exists (select 1 from public.boxes b where b.id = v_box_id) then
      raise exception 'box_not_found';
    end if;
  end if;

  return query
  select
    l.id,
    l.actor_id,
    l.actor_email,
    l.action_name,
    l.action_status,
    l.box_id,
    l.source,
    l.details,
    l.created_at
  from public.operator_action_log l
  where (v_status is null or l.action_status = v_status)
    and (v_box_id is null or l.box_id = v_box_id)
    and (v_from_ts is null or l.created_at >= v_from_ts)
    and (v_until_ts is null or l.created_at <= v_until_ts)
    and (
      v_search is null
      or l.action_name ilike '%' || v_search || '%'
      or l.action_status ilike '%' || v_search || '%'
      or coalesce(l.source, '') ilike '%' || v_search || '%'
      or coalesce(l.actor_email, '') ilike '%' || v_search || '%'
      or l.actor_id::text ilike '%' || v_search || '%'
      or coalesce(l.details::text, '') ilike '%' || v_search || '%'
      or (l.box_id is not null and ('box ' || l.box_id::text) ilike '%' || v_search || '%')
    )
  order by l.created_at desc, l.id desc
  offset v_offset
  limit v_limit;
end;
$$;

revoke all on function public.log_operator_action(text, text, integer, jsonb, text) from public;
revoke all on function public.list_operator_actions(integer) from public;
revoke all on function public.list_operator_actions_filtered(integer, integer, text, integer, text, timestamptz, timestamptz) from public;

grant execute on function public.log_operator_action(text, text, integer, jsonb, text) to authenticated;
grant execute on function public.list_operator_actions(integer) to authenticated;
grant execute on function public.list_operator_actions_filtered(integer, integer, text, integer, text, timestamptz, timestamptz) to authenticated;

commit;

notify pgrst, 'reload schema';
